import hashlib
import json
from datetime import datetime, timezone
from typing import Dict, List, Optional


def generate_evidence_package(
    campaign: Dict,
    entities: List[Dict],
    events: List[Dict],
    recipient: Optional[str] = None,
    package_type: str = "STANDARD"
) -> Dict:
    """
    Generate a legally-formatted evidence package for a campaign.
    Suitable for submission to law enforcement, EU institutions, or courts.
    """

    timestamp = datetime.now(timezone.utc).isoformat()

    package = {
        "metadata": {
            "package_id": None,  # Will be set on save
            "generated_at": timestamp,
            "generated_by": "ATIP — Agentic Threat Intelligence Platform",
            "platform_version": "0.2.0",
            "package_type": package_type,
            "recipient": recipient or "UNSPECIFIED",
            "classification": _get_classification(package_type),
            "legal_notice": (
                "This evidence package was generated by automated threat intelligence analysis. "
                "All findings are based on publicly available data and behavioral analysis. "
                "This document may be used as supporting evidence in legal proceedings. "
                "ATIP is operated by Neuronium Engineers GbR, Frankfurt am Main, Germany. "
                "Contact: legal@neuronium.ai"
            ),
        },
        "campaign": {
            "id": str(campaign.get("id", "")),
            "name": campaign.get("name", ""),
            "status": campaign.get("status", ""),
            "threat_level": campaign.get("threat_level", ""),
            "target": campaign.get("target", ""),
            "target_type": campaign.get("target_type", ""),
            "first_detected": str(campaign.get("first_detected", "")),
            "last_activity": str(campaign.get("last_activity", "")),
            "entity_count": campaign.get("entity_count", 0),
            "coordination_score": campaign.get("coordination_score", 0),
            "tactics": campaign.get("tactics", []),
            "summary": campaign.get("summary", ""),
        },
        "entities": [
            {
                "id": str(e.get("id", "")),
                "input": e.get("entity_input", ""),
                "type": e.get("entity_type", ""),
                "role": e.get("role", ""),
                "threat_score": e.get("threat_score", 0),
                "first_seen": str(e.get("first_seen", "")),
                "last_seen": str(e.get("last_seen", "")),
                "activity_count": e.get("activity_count", 1),
                "ip_addresses": e.get("ip_addresses", []),
                "platforms": e.get("platforms", []),
                "signals": e.get("signals", []),
            }
            for e in entities
        ],
        "timeline": [
            {
                "timestamp": str(ev.get("created_at", "")),
                "event_type": ev.get("event_type", ""),
                "severity": ev.get("severity", ""),
                "description": ev.get("description", ""),
            }
            for ev in sorted(events, key=lambda x: str(x.get("created_at", "")))
        ],
        "statistical_summary": _build_stats(entities),
        "recommendations": _build_recommendations(campaign, entities),
    }

    # Generate tamper-evident hash
    content_str = json.dumps(package, sort_keys=True, default=str)
    package_hash = hashlib.sha256(content_str.encode()).hexdigest()
    package["integrity"] = {
        "hash_algorithm": "SHA-256",
        "hash": package_hash,
        "timestamp": timestamp,
        "note": "This hash can be used to verify the integrity of this evidence package."
    }

    return package


def _get_classification(package_type: str) -> str:
    classifications = {
        "STANDARD": "TLP:WHITE — Unrestricted distribution",
        "LAW_ENFORCEMENT": "TLP:GREEN — Law enforcement only",
        "GOVERNMENT": "TLP:AMBER — Government agencies only",
        "CLASSIFIED": "TLP:RED — Named recipients only",
    }
    return classifications.get(package_type, "TLP:WHITE")


def _build_stats(entities: List[Dict]) -> Dict:
    if not entities:
        return {}

    threat_scores = [e.get("threat_score", 0) for e in entities]
    entity_types = {}
    roles = {}
    all_platforms = []
    all_ips = []

    for e in entities:
        t = e.get("entity_type", "UNKNOWN")
        entity_types[t] = entity_types.get(t, 0) + 1
        r = e.get("role", "ACTOR")
        roles[r] = roles.get(r, 0) + 1
        all_platforms.extend(e.get("platforms", []))
        all_ips.extend(e.get("ip_addresses", []))

    return {
        "total_entities": len(entities),
        "average_threat_score": round(sum(threat_scores) / len(threat_scores), 1),
        "max_threat_score": max(threat_scores),
        "min_threat_score": min(threat_scores),
        "entity_type_distribution": entity_types,
        "role_distribution": roles,
        "unique_platforms": list(set(all_platforms)),
        "unique_ips": list(set(all_ips)),
        "total_activity_count": sum(e.get("activity_count", 1) for e in entities),
    }


def _build_recommendations(campaign: Dict, entities: List[Dict]) -> List[Dict]:
    recs = []
    threat_level = campaign.get("threat_level", "LOW")
    tactics = campaign.get("tactics", [])

    if threat_level in ["HIGH", "CRITICAL"]:
        recs.append({
            "priority": "IMMEDIATE",
            "action": "Report to relevant authorities",
            "details": "Submit this evidence package to national cybersecurity agency (BSI, CERT, or equivalent)",
            "recipients": ["BSI (Germany)", "CERT-EU", "Europol EC3", "Local law enforcement"]
        })

    if "Narrative Manipulation" in tactics:
        recs.append({
            "priority": "HIGH",
            "action": "Platform reporting",
            "details": "Report coordinated inauthentic behavior to affected platforms",
            "recipients": ["Platform Trust & Safety teams", "EU DSA enforcement bodies"]
        })

    if "Phishing / Identity Spoofing" in tactics:
        recs.append({
            "priority": "HIGH",
            "action": "Domain takedown",
            "details": "Request domain suspension from registrar and hosting provider",
            "recipients": ["Domain registrar abuse team", "Hosting provider abuse team", "ICANN"]
        })

    if campaign.get("coordination_score", 0) > 0.6:
        recs.append({
            "priority": "MEDIUM",
            "action": "Intelligence sharing",
            "details": "Share campaign indicators with threat intelligence community",
            "recipients": ["MISP community", "EU INTCEN", "NATO CCDCOE"]
        })

    recs.append({
        "priority": "ONGOING",
        "action": "Continue monitoring",
        "details": "Monitor for new entities joining the campaign and infrastructure changes",
        "recipients": ["ATIP Campaign Tracker"]
    })

    return recs
